### PR TITLE
Change 'size()' function calls to 'length'

### PR DESCRIPTION
**Pull request by freemer**
size() has been removed from jQuery 3

### CODE REVIEW

**Comment by steveyj79** [comment]
nice fix

**Comment by priley86** [comment]
+1, would like to see this fix

**Comment by meijdenmedia** [comment]
When will this fix be deployed?

**Comment by steveyj79** [comment]
it won't until the tests are fixed the CI build is failing

**Comment by tsneed290** [comment]
Forgive me @steveyj79 if I am misunderstanding the failing build. Why would the two commits in this pull request have anything to do with Travis throwing an NPM "EPEERINVALID" error code?

Eagerly awaiting this fix :)

Regards,
T

**Comment by steveyj79** [comment]
@tsneed290 not sure why could of been built on an older version of the branch i've not checked whats actually failing in the build, just know the build won't be merged until; the tests have been fixed. by all means try forking off the last release applying the same fix and see if the build fails or not

**Comment by tsneed290** [comment]
Thanks @steveyj79, should have some time to try tha

**Comment by tsneed290** [comment]
Hey @steveyj79, created a new pull request that passes #1726. Let me know if you see any problems.

**Comment by steveyj79** [comment]
new fix https://github.com/Eonasdan/bootstrap-datetimepicker/pull/1726

**Comment by Synchro** [comment]
This build failure looks like a Travis-Ci env issue, nothing to do with this PR. Restarting it may work.

**Comment by nickel715** [comment]
The size()/length fix is already done in 0202134

**Pull request closed without merging**
