### PR TITLE
Allow readonly input

### PR DESCRIPTION
**Pull request by tsjoberg**
Allow readonly input state to allow datepicker

### CODE REVIEW

**Comment by tsjoberg** [comment]
fixes issue https://github.com/Eonasdan/bootstrap-datetimepicker/issues/764

**Comment by nikoskalogridis** [comment]
There was a discussion on #212 regarding the functionality of the readonly attribute on the input field. I once again would like to express my objection for changing the html semantics of readonly on an input field. I will leave this to @Eonasdan to decide though :)

**Comment by yanickrochon** [comment]
I can see the rationale behind not allowing the control to modify the input field if it is marked as `readonly`. If you think about it, it is "read only", so being able to modify it, by default, is kinda contrary to the field's attribute...  However, the proper change would be to override this behaviour with a initialization option. Something that would tell the widget to ignore the readonly state of the input field and allow modifying it anyway (by design).

**Comment by tsjoberg** [comment]
@nikoskalogridis I can understand the reasoning and the semantics around "readonly" but I have been doing some additional research and it seems the only way for virtual keyboards (mobile devices, ipads, etc) to not pop up is to use the readonly attribute. I have been looking at other datepicker implementations and they all seem to follow suit by using readonly attribute.

I know this library may not be targeted at mobile/tablet/phablet audiences but not sure if this "workaround" for virtual keyboards is a valid reason to merge?

**Comment by ahmader** [comment]
I use readonly in all my datetimepicker objects. I liked @yanickrochon approach
```javascript
{editable: true}
```
For now I will use @tsjoberg commit as v4 broke my project.

**Comment by yanickrochon** [comment]
@ahmader I got around this particular scenario by implementing [a very basic solution](https://github.com/Eonasdan/bootstrap-datetimepicker/issues/764#issuecomment-72793119). I guess this could be implemented inside the widget with your `editable` option?

**Comment by ahmader** [comment]
@yanickrochon Yes I saw your proposed solution but honestly couldn't understand how to implement it.

If you have some spare time, can you please rewrite it on a more generic example?. Thanks.

**Comment by yanickrochon** [comment]
Well, something along the lines of 

```js
picker.allowManualEditing = function (allowManualEditing) {
    var events;
    var eventNS = 'datetimepicker';
    var eventTypes = ['keypress', 'paste'].map(function (eventType) { 
        return eventType + '.' + eventNS;
    }).join(' ');
    var eventsAttached = false;

    if (arguments.length === 0) {
        return options.allowManualEditing;
    }

    if (typeof allowManualEditing !== 'boolean') {
        throw new TypeError('allowManualEditing() expects a boolean parameter');
    }

    options.allowManualEditing = allowManualEditing;
    if (allowManualEditing) {
      input.off(eventTypes, disableEvent);
    } else {
        events = input.data('events');
        events && $.each(events, function (event, data) {
            if (data.namespace === eventNS && data.handler === disableEvent) {
                eventsAttached = true;
            }
        });

        // prevent adding event twice
        if (!eventsAttached) {
            input.on(eventTypes, disableEvent);
        }
    }

    return picker;
};

function disableEvent(e) {
    e.preventDefault();
    e.stopPropagation();
    e.stopImmediatePropagation();
    return false;
}
```

then

```js
$.fn.datetimepicker.defaults = {
    ...
    allowManualEditing: true,   // come to think of it, the semantic is better this way IMO
    ...
};
```

This will simply not allow the user to modify the input field manually. However, I wrote this without actually running it, so this is mostly an implementation draft :)

**Comment by ahmader** [comment]
Thanks @yanickrochon your example was very helpful. however, after testing it, I remembered I still need read-only for mobile to not trigger the keyboard. So I used your example, and implemented a PR to development branch to add this feature as per @nikoskalogridis suggested rules.
```javascript
options.disallowReadOnly = false; // default (true)
```

**Comment by yanickrochon** [comment]
@ahmader Good point about the field not triggering the keyboard... A `focus` event could have fixed that, too, I guess. :)

I'm still not convinced of the option name, though : `disallowReadonly: true`, `enforceReadonly: true`, or `ignoreReadonly: false`, etc.

It might be because english is not my first language, but I have to carefully think what is the proper value for "disallow" a "readonly" field; is it `true`, or `false`? Personally, "ignoring" a "readonly" field is more intuitive... IMO.

**Comment by tsjoberg** [comment]
@ahmader I agree with @yanickrochon on the wording, maybe ```editable: true``` is more appropriate (default is ```editable:true```)? Would even go one step further and if ```editable:false``` the picker would add the readonly attribute on the initialization? Thoughts?

**Comment by yanickrochon** [comment]
@tsjoberg what if the input field's `readonly` attribute is set and the option `editable: false` is provided, what then? Does select2 remove the attribute? I think it's not desirable and the options should only modify behaviour and not semantic (i.e. it should not modify the original element's configuration)

**Comment by tsjoberg** [comment]
@yanickrochon I can agree with that point and maybe in those cases it should throw an appropriate error. However, there are current plugin functions like enabled() and disabled() that do modify the original element by adding or removing the appropriate classes and I was thinking along those same lines. 

I guess its just a decision on whether the element should be fully controlled by the datepicker and having full control of its properties etc or more to your point that it shouldn't mess around with whatever is there previously.

Also I think this ```editable:``` option could even be expanded to create hidden element like you have in your example so that form submits etc are still working. Again a lot of these ideas are not mine originally but just looking at how other datepicker plugins are being implemented!

**Comment by yanickrochon** [comment]
@tsjoberg what I mean is, that the point in question, here, is that when `readonly` is set, the widget should still allow editing it's value regardless. Therefore, it's not only a matter of "should it mess around with the attribute or not", but rather "should it redefine the readonly attribute or not". I think it should not. The `disabled` and `enabled` state is not redefined, here, so it does not apply; we are saying that, when `readonly` is set, *sometimes*, there are cases where the input should *still* be edited, but the default should be *not*.

**Comment by tsjoberg** [comment]
@yanickrochon I agree with you that I do not want to redefine states but I think our definitions of "readOnly" might be different. To me, readOnly refers to just an input attribute to not be able to edit the value - not necessarily the value may not change by another action. I do think your case of if someone is using a readOnly input and setting ```editable:true``` should be accounted for but in that case I cannot think of a use case where a developer would knowingly set the input ```readOnly``` to true and also set the ```editable:true``` option if it existed.

I think I am just disagreeing with your last point:

> "we are saying that, when readonly is set, sometimes, there are cases where the input should still be edited, but the default should be not." 

I think there is no case where readonly is set and the input should still be editable.

Also the ```editable:true``` may not be an init option but maybe a picker function same as enabled() and disabled() to change state based on picker function?

**Comment by ahmader** [comment]
I agree too with the option rename (ignoreReadOnly:false). The name "editable" sound like it will change the actual element behavior as mentioned. I wanted to make the option as a simple bypass of the controller standard behavior. also in all my projects I use readonly for datepickers with no extra js for mobile keyboards it make my code more cleaner :smile: 
@Eonasdan , @nikoskalogridis  any thoughts or plans on how to deal with this ?

**Comment by Eonasdan** [comment]
merged #828 closing

**Comment by yanickrochon** [comment]
I still think `ignoreReadonly` is better than `disallowReadonly`. IMO.

**Comment by Eonasdan** [comment]
@yanickrochon I agree. I'll change it with some other work I'm doing.

**Comment by mohsinraza** [comment]
Hey @yanickrochon

`readonly=true` works when I was using [bootstrap-datepicker](https://github.com/eternicode/bootstrap-datepicker) in my web app but it was not working for [bootstrap-datetimepicker](https://github.com/Eonasdan/bootstrap-datetimepicker). 

Issue I was facing is: ``when user use the website from smartphone device then device keyboard scrolls up and actual datetimepicker goes out of control. this was very painful. ``

I don't know how you are trying/handling this. but I have added a quick fix to my code that works as below.

```html
<div class='input-group date datetimepicker1' >
       <input type="text" class="hidden">
       <input type='text' class="form-control" readonly="true" id="for_date" name="for_date" value="<?= set_value('for_date'); ?>" />
       <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
       </span>
 </div>
```
I am using two fields for this purpose. 
field one is hidden text field while second field is the real field but it is readonly. 

This works for me because I don't want to show smartphone keyboard to user which was very painful. Let me know if there is a better solution to achieve the same. This also not allowing to input from desktop/laptop as well now which is cool like [bootstrap-datepicker](https://github.com/eternicode/bootstrap-datepicker) :smile:

**Comment by Henri-K** [comment]
@mohsinraza this actually works for now. thanks!

**Comment by CalmCoders** [comment]
You can prevent user to enter text into text box manually by using the following:


<script>
        $(document).ready(function () {
            $("#txtFromDate").keypress(function (event) { event.preventDefault(); });
    </script>


#txtFromDate-- Id of the textbox

**Comment by bookreev** [comment]
ios8 don't works! (readonly="true")

**Comment by clabnet** [comment]
Using ignoreReadonly and readonly the field and calendar icon is readonly and disabled.
I think it is an issue; it is useful forcing the user to pick the date from calendar and not insert manually the date. 
See JSFiddle http://jsfiddle.net/clabnet/4zfz1nnx/#base

**Comment by yanickrochon** [comment]
@clabnet , You should open a new issue, as this has nothing to do with the subject, here.

Your problem is that the function `dataToOptions` is prepending `date` to all `data-*` attributes... thus ignoring about half of the options set via HTML.

For instance, here, `data-ignore-readonly="false"` is correctly converted into `{ ignoreReadonly: false }` by jQuery (note: is should actually be `data-ignore-readonly="true"`.... just saying) but the widget checks for an option named `dateIgnoreReadonly`... which obviously does not exist, and skip it.

Just check it out yourself. The problem is at line [352](https://github.com/Eonasdan/bootstrap-datetimepicker/blob/805bcc39f3e30a54f350a556c727f73f1e07394b/src/js/bootstrap-datetimepicker.js#L352) in the source code. Thus, totally an issue, but irrelevant to this one.

**Pull request closed without merging**
