### PR TITLE
Added selection of multiple dates

### PR DESCRIPTION
**Pull request by bodrick**
My attempt at selecting multiple dates from a date picker, I've not implemented any testing yet for the new functionality, I plan on doing that next, but my initial testing seems to have proven successful.  Take a look and let me know what you think, it no doubt needs some tweaking but I expect to do that as I true to utilize it in the project I'm working on.

### CODE REVIEW

**Comment by bodrick** [comment]
I also have added better handling of enable and disable for inline datepickers.

**Comment by sdigihey** [comment]
I have been testing it and while picker part works fine, cant get it to set existing dates from input value.

**Comment by sdigihey** [comment]
Replace at line 2556
```
if (input.is('input') && input.val().trim().length !== 0) {
            setValue(parseInputDate(input.val().trim()));
        }
```
with
```
if (input.is('input') && input.val().trim().length !== 0) {
            if (options.multiDate) {
                setValue(parseInputDate(input.val().trim().split(options.multiDateDelimiter)));
            } else {
                setValue(parseInputDate(input.val().trim()));
            }
          
        }
```
Looks like this fixes initialization problem

**Comment by marianacapelo** [comment]
+1
Any plans to resolve the conflicts?

**Comment by matlow** [comment]
@bodrick it could be merge ?

**Comment by bodrick** [comment]
So I finally updated my branch and so the merge should work now without any issues.  Going forward if there is no action on this I will continue to update my fork.

**Pull request closed without merging**
