### PR TITLE
Introduce sass support

### PR DESCRIPTION
**Pull request by nervo**

### CODE REVIEW

**Comment by Ilyes512** [comment]
I was about to create an issue to ask if I got submit a PR for SASS support, but I see it's already added to the dev branch. Will it be merged to the master branch any time soon?

**Comment by Ilyes512** [comment]
Actually. I see its removed? Is there a specific reason and can I make a new PR incase it's removed cause of issues? I want to prevent having to fork and add it to bower.

**Comment by Eonasdan** [comment]
@Ilyes512 this was probably committed to the v3 dev branch and didn't make it back into v4. You're welcome to put in a PR to the development branch

**Comment by Ilyes512** [comment]
Great! I will PR it tomorrow or the day after :)!

**Pull request merged**
