### PR TITLE
Keyboard accessibility

### PR DESCRIPTION
**Pull request by kikonen**
- FIX don't steal focus from the field when TABin to field
- FIX don't eat keys when popup is not shown
- FIX try to retain focus so that keyboard editability works

### CODE REVIEW

**Comment by lustremedia** [comment]
Yes please merge this!

**Comment by kikonen** [comment]
@lustremedia I hope you were not targeting that message to me since I don't have merge rights in this repository.

**Comment by kikonen** [comment]
@Eonasdan ?

**Comment by lustremedia** [comment]
@kikonen no I was not targeting you, more I was hoping that @Eonasdan would see this and move in on it!

**Comment by Eonasdan** [comment]
Per the [contrib doc](https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/CONTRIBUTING.md#very-important-notes), please make your PRs to the development branch. PRs to the master will be closed.

**Comment by kikonen** [comment]
Looking into history of repo (ex. #1887) sounds a bit unfair, but retrying... and noticed that "development" and "master" branches are out of sync.

**Comment by kikonen** [comment]
@Eonasdan so what I'm supposed to do with the fact that development and master branches differ from each other?

**Comment by Eonasdan** [comment]
well I guess if you would have read the contrib doc which clearly states to put your PRs into the dev branch, you wouldn't have to worry.

also 1187 is a change that directly effects downloading/install/modules versus a code change.

**Comment by kikonen** [comment]
You may guess that being tricky, since I needed changes into production, applied in top of stable baseline.

Retried into development in #1916 by cherry picking them into "development" based branch. However, I can't test changes on that branch in real life.

**Pull request closed without merging**
