### PR TITLE
Update function useCurrent, added endDay option.

### PR DESCRIPTION
**Pull request by EltonRst**
'endDay' option provides hour 23:59:59.

'endDay': function (m) {
    return m.hours(23).seconds(59).minutes(59);
},

### CODE REVIEW

**Comment by EltonRst** [comment]
I'll check and correct the errors and commit again.

**Comment by EltonRst** [comment]
@Eonasdan Eonasdan, Can you help me with this option?

**Comment by EltonRst** [comment]
@Eonasdan Sorry, I found the error, I'm opening a new pull request.

**Comment by William-H-M** [comment]
For what use will be the use this? I mean you can just easily use `moment.endOf('day');`

**Comment by EltonRst** [comment]
@William-H-M 
```
$('#my-input-end-date').datetimepicker({
        format: 'DD/MM/YYYY HH:mm',
        locale: 'pt-br',
        useCurrent: moment.endOf('day')
    });
```
`Uncaught TypeError: moment.endOf is not a function`

I tried:
` useCurrent: moment().endOf('day')`
But: 
`Uncaught TypeError: useCurrent() expects a boolean or string parameter`

My idea is to have a range where the time starts 00:00:00 and finish 23:59:59
to apply to a start and end filter, and the change I made was the easiest way to resolve it.

```
$('#my-input-initial-date').datetimepicker({
        format: 'DD/MM/YYYY HH:mm',
        locale: 'pt-br',
        useCurrent: 'day'
    });
    $('#my-input-end-date').datetimepicker({
        format: 'DD/MM/YYYY HH:mm',
        locale: 'pt-br',
        useCurrent: 'dayend'
    });
```

**Comment by EltonRst** [comment]
@William-H-M 
I could use:

`defaultDate: moment().endOf('day')`

But I need this field to boot empty, and when the user clicks come 00:00:00 on the initial and 23:59:59 on the end.

**Comment by William-H-M** [comment]
> Uncaught TypeError: moment.endOf is not a function

My bad the code was `moment().endOf('day')`

> My idea is to have a range where the time starts 00:00:00 and finish 23:59:59

That's basically the whole idea of [`minDate`](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#mindate) and [`maxDate`](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#maxdate)

**Comment by EltonRst** [comment]
@William-H-M 

Almost there, I do not want to limit the selection of dates, I want the date selection to be free, but in the initial filter when it is clicked on a day, the time starts with 00:00:00, and when it is the end date filter the date starts 23:59:59.

image

Data Inicial = Initial Date/Time
Data Final= End Date/Time

 Example:
image

**Comment by William-H-M** [comment]
Mmmm you should discuss this on the new repo it could be a good idea, I guess. https://github.com/tempusdominus/bootstrap-4, but I'm sure it's not gonna be merge on this repo as is currently on code-freeze only emergency fixes will be done, if found.

**Pull request closed without merging**
