### PR TITLE
Fix time is reset to current when date is changed

### PR DESCRIPTION
**Pull request by trask**
Do you see any issue with uncommenting this line?  Thanks

### CODE REVIEW

**Comment by trask** [comment]
This may be same issue as #1884

**Comment by suprduprmn** [comment]
When is this scheduled to be merged?

**Comment by suprduprmn** [comment]
Pinging this again? Going on almost a month with this ready to be merged.  Can it be?  Really would like to fix this issue as it is a HUGE pain.

**Comment by Magikos** [comment]
I am awaiting this fix also.

**Pull request closed without merging**
