### PR TITLE
Add an option to set the expanded class of Bootstraps collapse

### PR DESCRIPTION
**Pull request by RodolfoSilva**
Solve problems with bootstrap 4.

In Bootstrap 4, the .in class will be renamed to .show.

Maybe this class must be seted by user.

### CODE REVIEW

**Comment by RodolfoSilva** [comment]
@Eonasdan Why this PR has closed?

**Comment by Eonasdan** [comment]
Because there's a new bs4 repo and this repo is going into feature/code freeze

**Comment by RodolfoSilva** [comment]
@Eonasdan What's the new repo?

**Comment by Eonasdan** [comment]
https://github.com/tempusdominus/bootstrap-4

**Comment by RichardD2** [comment]
The link to the new repo is not particularly easy to find. Perhaps you could add it to this repo's "readme" file?

**Pull request closed without merging**
