### PR TITLE
Fix peerDependency build issue & change size() to length

### PR DESCRIPTION
**Pull request by tsneed290**
This fixes the build issue as part of #1664.

### CODE REVIEW

**Comment by steveyj79** [comment]
looks good to me, hopefully it can be merged and a new build done

**Comment by tsneed290** [comment]
I just commented on the original ticket. This doesn't actually work as intended, the date time picker pop up is blank. Will cancel and investigate further.

**Comment by steveyj79** [comment]
ah okay :(

**Comment by tsneed290** [comment]
Ugh, it was my own environmental issues. Going through an upgrade and had some old CSS leaking through that prevented the calendar picker from displaying. 

Re-opening, sorry for that.

**Comment by steveyj79** [comment]
least it works thats all that matters, good work, not sure how you get it signed off to be deployed

**Comment by steveyj79** [comment]
@Eonasdan

**Comment by tsneed290** [comment]
Hi @Eonasdan, this fixes an issue where jQuery 3.0 was not supported. I just read your contributing guide, please let me know if you wish me to switch this PR to the development branch.

As an aside, what is the release schedule? We depend on this project via NPM and it looks like a release hasn't occurred since 2015.

Regards,
T

**Comment by steveyj79** [comment]
@tsneed290 i think the pull request needs to point to development not master

> Very important notes

Pull requests to the master branch will be closed. Please submit all pull requests to the development branch.
Do not include the minified files in your pull request. Don't worry, we'll build them when we cut a release.
Pull requests that do not include a description (title only) and the following will be closed:
What the change does
A use case (for new features or enhancements)

**Comment by tsneed290** [comment]
Thanks @steveyj79, will move it.

**Comment by tsneed290** [comment]
@steveyj79 it looks like the development branch has the fixes needed to support jQuery 3. 

While not desired, I am able to depend on the project in my package.json by referencing the git commit hash:

     "dependencies": {
        "eonasdan-bootstrap-datetimepicker": "git://github.com/Eonasdan/bootstrap-datetimepicker.git#d4971777a957d1d3134b1d90a695a3169111f65f",
      }


@Eonasdan When do you think you'll be releasing 4.17.42 to NPM's registry?

**Comment by Eonasdan** [comment]
dev is now master and updated in npm

**Comment by steveyj79** [comment]
Cheers @eonasdan

**Comment by tsneed290** [comment]
Thanks @Eonasdan!!

**Comment by jnm2** [comment]
@Eonasdan, since this is a hotfix, could you please replace the buggy one currently at NuGet?

**Comment by ramin25** [comment]
Can this be updated in bower please? bower still shows and pushes version 4.17.37 as the latest which uses input.size.

**Comment by virzen** [comment]
Wouldn't creating a tag solve the issue with bower which @ramin25 mentioned?

**Comment by CarlosRuizTinamica** [comment]
4.17.42 still not avaiable in bower. Any news on this?

image

**Comment by meijdenmedia** [comment]
@Eonasdan can you please create a new tag so we can get the changes via bower?

**Comment by elanclarkson** [comment]
@tsneed290 
> Ugh, it was my own environmental issues. Going through an upgrade and had some old CSS leaking through that prevented the calendar picker from displaying.

Re-opening, sorry for that.

This actually appears to be a real issue in jQuery 3.1 that has been reported here #1765.

**Comment by osbeug001** [comment]
For bower users who are not aware, there is version 4.17.45 which works.

**Pull request closed without merging**
