### PR TITLE
New option: periodPlacement

### PR DESCRIPTION
**Pull request by iwaim**
I choise place for togglePeriod button.

Because 'am/pm" is first in Japanese.

English       | Japanese
-------------- | -------------
AM             | 午前 
PM             | 午後
10:00 a.m. | 午前10時
3:45 p.m.   | 午後3時45分

### CODE REVIEW

**Comment by Eonasdan** [comment]
Thanks for the PR, but this is probably a momentjs issue or you aren't including the correct locale file.

Did you set the `locale` option?

**Comment by iwaim** [comment]
@Eonasdan Thanks for your review.

I set the locale option with bootstrap-datetimepicker, but it don't give my expectant view in timepicker. [1]

version 4.17.37 | my expectant view
--------------------|-------------------------
12:00 午前        | 午前 12:00

momentjs 2.11.2 with locale gives my expectant view. [2]

[1] https://jsfiddle.net/iwaim/6sqzpLcg/3/
[2] https://jsfiddle.net/iwaim/h68ktknt/

**Comment by Eonasdan** [comment]
The plugin use moment to provide the locale formatting. I still think that this should be a momentjs issue to patch the `ja` locale file. If they won't fix it, I'll pull the PR. I'm just trying to save you and other an extra configuration option if it really needs to be fixed else where.

**Comment by iwaim** [comment]
I see. I will study the moomentjs, its issues and PR.
Thanks.

**Comment by Eonasdan** [comment]
If you open an issue on [momentjs](https://github.com/moment/moment) please link this issue so I can monitor it as well.

**Comment by iwaim** [comment]
Okey.

**Pull request closed without merging**
