### PR TITLE
Fix issue #1802

### PR DESCRIPTION
**Pull request by diegosurita**
Fix the error described on issue #1802.

### CODE REVIEW

**Comment by pascal-hofmann** [comment]
@Eonasdan This fix is in master and development branch for quite some time, but somehow not in the latest release.

https://github.com/Eonasdan/bootstrap-datetimepicker/blob/4.17.44/src/js/bootstrap-datetimepicker.js#L950

Would be great to have this in the released version. A lot of people seem to have problems with this. (#1960, #1894, #1914, #1897, #1865, ...)

**Comment by ReyRod** [comment]
Need this in the release version, i don't want to go live with a temporary fix.

**Comment by Eonasdan** [comment]
pushed 4.17.45

**Comment by GuilhermeHideki** [comment]
Looks like this fix isn't in 4.17.45 or master.

https://github.com/Eonasdan/bootstrap-datetimepicker/blob/v4.17.45/src/js/bootstrap-datetimepicker.js#L950

https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L950

Should this line be erased or changed like
https://github.com/Eonasdan/bootstrap-datetimepicker/pull/1854 ?

**Comment by pascal-hofmann** [comment]
@Eonasdan Somehow the fix always refuses to get into the released versions. Can you have a look at this again?

Thanks

**Pull request merged**
